import random
import turtle
scn=turtle.Screen()
t=turtle.Turtle()
t.penup()

def italy():
    t.penup()
    t.goto(-100, 80)
    t.fillcolor("green")
    t.begin_fill()
    for i in range(2):
        t.fd(30)
        t.rt(90)
        t.fd(50)
        t.rt(90)
    t.end_fill()
    t.penup()
    t.goto(-70,80)
    t.pendown()
    t.fillcolor("white")
    t.begin_fill()
    for i in range(2):
        t.fd(30)
        t.rt(90)
        t.fd(50)
        t.rt(90)
    t.end_fill()
    t.penup()
    t.goto(-40, 80)
    t.pendown()
    t.fillcolor("red")
    t.begin_fill()
    for i in range(2):
        t.fd(30)
        t.rt(90)
        t.fd(50)
        t.rt(90)
    t.end_fill()

def france():
    t.penup()
    t.goto(-100, 80)
    t.fillcolor("blue")
    t.begin_fill()
    for i in range(2):
        t.fd(30)
        t.rt(90)
        t.fd(50)
        t.rt(90)
    t.end_fill()
    t.penup()
    t.goto(-70, 80)
    t.pendown()
    t.fillcolor("white")
    t.begin_fill()
    for i in range(2):
        t.fd(30)
        t.rt(90)
        t.fd(50)
        t.rt(90)
    t.end_fill()
    t.penup()
    t.goto(-40, 80)
    t.pendown()
    t.fillcolor("red")
    t.begin_fill()
    for i in range(2):
        t.fd(30)
        t.rt(90)
        t.fd(50)
        t.rt(90)
    t.end_fill()

def belgium():
    t.penup()
    t.goto(-100, 80)
    t.fillcolor("black")
    t.begin_fill()
    for i in range(2):
        t.fd(30)
        t.rt(90)
        t.fd(50)
        t.rt(90)
    t.end_fill()
    t.penup()
    t.goto(-70, 80)
    t.pendown()
    t.fillcolor("yellow")
    t.begin_fill()
    for i in range(2):
        t.fd(30)
        t.rt(90)
        t.fd(50)
        t.rt(90)
    t.end_fill()
    t.penup()
    t.goto(-40, 80)
    t.pendown()
    t.fillcolor("red")
    t.begin_fill()
    for i in range(2):
        t.fd(30)
        t.rt(90)
        t.fd(50)
        t.rt(90)
    t.end_fill()

def bulgaria():
    t.penup()
    t.goto(-100, 80)
    t.pendown()
    t.fillcolor("white")
    t.begin_fill()
    for i in range(2):
        t.fd(120)
        t.rt(90)
        t.fd(30)
        t.rt(90)
    t.end_fill()
    t.penup()
    t.goto(-100, 50)
    t.pendown()
    t.fillcolor("green")
    t.begin_fill()
    for i in range(2):
        t.fd(120)
        t.rt(90)
        t.fd(30)
        t.rt(90)
    t.end_fill()
    t.penup()
    t.goto(-100, 20)
    t.pendown()
    t.fillcolor("red")
    t.begin_fill()
    for i in range(2):
        t.fd(120)
        t.rt(90)
        t.fd(30)
        t.rt(90)
    t.end_fill()

def germany():
    t.penup()
    t.goto(-100, 80)
    t.fillcolor("black")
    t.begin_fill()
    for i in range(2):
        t.fd(120)
        t.rt(90)
        t.fd(30)
        t.rt(90)
    t.end_fill()
    t.penup()
    t.goto(-100, 50)
    t.pendown()
    t.fillcolor("red")
    t.begin_fill()
    for i in range(2):
        t.fd(120)
        t.rt(90)
        t.fd(30)
        t.rt(90)
    t.end_fill()
    t.penup()
    t.goto(-100, 20)
    t.pendown()
    t.fillcolor("yellow")
    t.begin_fill()
    for i in range(2):
        t.fd(120)
        t.rt(90)
        t.fd(30)
        t.rt(90)
    t.end_fill()

def estonia():
    t.penup()
    t.goto(-100, 80)
    t.pendown()
    t.fillcolor("blue")
    t.begin_fill()
    for i in range(2):
        t.fd(120)
        t.rt(90)
        t.fd(30)
        t.rt(90)
    t.end_fill()
    t.penup()
    t.goto(-100, 50)
    t.pendown()
    t.fillcolor("black")
    t.begin_fill()
    for i in range(2):
        t.fd(120)
        t.rt(90)
        t.fd(30)
        t.rt(90)
    t.end_fill()
    t.penup()
    t.goto(-100, 20)
    t.pendown()
    t.fillcolor("white")
    t.begin_fill()
    for i in range(2):
        t.fd(120)
        t.rt(90)
        t.fd(30)
        t.rt(90)
    t.end_fill()

def poland():
    t.penup()
    t.goto(-100, 80)
    t.pendown()
    t.fillcolor("white")
    t.begin_fill()
    for i in range(2):
        t.fd(120)
        t.rt(90)
        t.fd(55)
        t.rt(90)
    t.end_fill()
    t.penup()
    t.goto(-100,25)
    t.pendown()
    t.fillcolor("red")
    t.begin_fill()
    for i in range(2):
        t.fd(120)
        t.rt(90)
        t.fd(55)
        t.rt(90)
    t.end_fill()

flags=[italy,france,belgium,bulgaria,germany,estonia,poland]
life=3
points=0
t.speed(100)

while life>0 and len(flags)>0:
    t.reset()
    flag=random.choice(flags)
    flag()

    answer=input("which country is this flag?")

    if answer==flag.__name__:
        flags.remove(flag)
        print("Bravo")
        points+=1
        print("Your points:",points)
        print("Your lives:", life)
    else:
        flags.remove(flag)
        print("Wrong")
        life-= 1
        print("Your life:", life)
        print("Your points:", points)

turtle.exitonclick()